version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: this_is_a_very_long_random_secret_key_123456
    volumes:
      - ./dags:/opt/airflow/dags
      - ./services:/opt/airflow/services
      - ./db:/opt/airflow/db
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    depends_on:
      - airflow-webserver
    env_file:
      - .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: this_is_a_very_long_random_secret_key_123456
    volumes:
      - ./dags:/opt/airflow/dags
      - ./services:/opt/airflow/services
      - ./db:/opt/airflow/db
    command: scheduler

volumes:
  postgres-db-volume:
